language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.cache/bower"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm i -g bower
  - yarn
  - bower install
script:
  - echo "Validating changes ..."
  - yarn run lint
